## Numpy
 It provides a high-performance multidimensional array object, and tools for working with these arrays.

<h3> Numpy Array </h3>
It is a grid of values, all of the same type.

In [12]:
A=np.array([2,3,4,5]) #create 1-D numpy array
A

array([2, 3, 4, 5])

In [14]:
A.shape  #shape of array

(4,)

In [15]:
A.dtype   #type of data stored in array

dtype('int32')

In [17]:
type(A)   #numpy array

numpy.ndarray

<b> Creating Arrays </b> using different numpy functions

In [20]:
#using python lists
A1=[2,3,4,5]
A2=[9,2,4,7]
A3=[4,1,7,3]
B=np.array([A1,A2,A3])
B

array([[2, 3, 4, 5],
       [9, 2, 4, 7],
       [4, 1, 7, 3]])

In [32]:
# creating arrays of zeros and ones
#array of zeros by defining size and data type
A4=np.zeros([3,4] , dtype=int)
print("Array of zeros: \n",A4)

# array of ones 
A5=np.ones([3,3],dtype=complex)
print("Array of ones: \n",A5)

Array of zeros: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Array of ones: 
 [[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [38]:
# creating array by defining the range and difference
A6=np.arange(20,60,5)
print(A6)

# creating array by defining the range and size 
A7=np.linspace(5,10,10)
A7

[20 25 30 35 40 45 50 55]


array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [66]:
# creating array by using random numbers
A8=np.random.rand(3,3)   #array having any random numbers from value 0 to 1
A8

array([[0.47164991, 0.0586086 , 0.42527427],
       [0.99410296, 0.8201669 , 0.50252526],
       [0.17323542, 0.87778119, 0.54379496]])

<b>Reshaping </b> arrays

In [41]:
B

array([[2, 3, 4, 5],
       [9, 2, 4, 7],
       [4, 1, 7, 3]])

In [42]:
B.shape  #shape of array

(3, 4)

In [47]:
#Reshaping
B=B.reshape(4,3)
B

array([[2, 3, 4],
       [5, 9, 2],
       [4, 7, 4],
       [1, 7, 3]])

<b> Changing </b> datatype of any array 

In [49]:
B.dtype

dtype('int32')

In [54]:
B=np.array(B,dtype=float)
print(B)
B.dtype

[[2. 3. 4.]
 [5. 9. 2.]
 [4. 7. 4.]
 [1. 7. 3.]]


dtype('float64')

<b> Indexing

In [71]:
print(B[1:,:2])

[[5. 9.]
 [4. 7.]
 [1. 7.]]


In [72]:
np.flip(B)  #reverse array

array([[3., 7., 1.],
       [4., 7., 4.],
       [2., 9., 5.],
       [4., 3., 2.]])

<b>Identity matrix 

In [74]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<b> Transpose of matrix

In [75]:
B.T

array([[2., 5., 4., 1.],
       [3., 9., 7., 7.],
       [4., 2., 4., 3.]])

<b> Basic Formula Results

In [76]:
# mean 
A=[20,34,12,65,67,39]
np.mean(A)

39.5

In [77]:
# standard devaiation
np.std(A)

20.710303393882636

In [79]:
# median
np.median(A)

36.5

In [80]:
np.max(A)

67

<b> Matrix Sum

In [86]:
A=np.array([[2,3,4],[3,5,7],[9,4,6]])
B=np.array([[12,5,3],[9,3,5],[2,1,5]])
A+B

array([[14,  8,  7],
       [12,  8, 12],
       [11,  5, 11]])

<b> Matrix Multiplication

In [87]:
np.dot(A,B)

array([[ 59,  23,  41],
       [ 95,  37,  69],
       [156,  63,  77]])

In [90]:
A*(B)

array([[24, 15, 12],
       [27, 15, 35],
       [18,  4, 30]])

In [ ]:
# we can easily do other mathetical operations very easily using this